<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StationeersLaunchPad</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
  </PropertyGroup>

  <Import Project="$(SolutionDir)SLP.common.props" />

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\Compatibility\StationeersMods.Interface\StationeersMods.Interface.csproj" />
    <ProjectReference Include="$(SolutionDir)\Compatibility\StationeersMods.Shared\StationeersMods.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\*.jpg;Images\*.png" LogicalName="StationeersLaunchPad.Images.%(Filename)%(Extension)" />
  </ItemGroup>

  <!-- the server zip ships the stub from Compatibility/RG.ImGui instead -->
  <ItemGroup>
    <Reference Include="RG.ImGui">
      <HintPath>$(StationeersManagedDirectory)\RG.ImGui.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>